name: Deploy to Cloudflare Pages

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pages-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.21'
    - name: Build
      run: mdbook build
    - name: Setup wrangler
      run: yarn global add wrangler
    - name: Deploy
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tirr-kb
          directory: book
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
